# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up Python 3.8
  #    uses: actions/setup-python@v2
  #    with:
  #      python-version: 3.8
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      python -m pip install flake8
  #  - name: Lint with flake8
  #    run: |
  #      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build_and_test_sdist:
    name: Test Wheel Python 3.8
    runs-on: ubuntu-latest
    #needs: [lint]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip 
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements/build.txt
        python -m pip install -r requirements/tests.txt
    - name: Build Wheel
      run: |
        python setup.py bdist_wheel
    - name: Install Wheel
      run: |
        cd dist
        ls -al
        pip install line_profiler*.whl -v
    - name: Test Wheel
      run: |
        pwd
        ls -al
        pytest

    - name: Upload Wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist/*.whl
